export const BASE_URL_USER_SERVICE = "http://localhost:8080/api/v1/user"
export const BASE_URL_COURSE_SERVICE = "http://localhost:8081/api/v1/course"
export const BASE_URL_TEACHER_MANAGEMENT_SERVICE ="http://localhost:8082/api/v1/teacher"
export const BASE_URL_REVIEW_SERVICE = "http://localhost:8083/api/v1/reviews"
export const BASE_URL_LECTURE_SERVICE = "http://localhost:8084/api/v1/lectures"
export const BASE_URL_PAYMENT_SERVICE = "http://localhost:8086/api/v1/payment"
export const BASE_URL_STATISTICAL_SERVICE = "http://localhost:8087/api/v1/statistical"