export const DOMAIN = "http://k8s-default-microser-29a0320a2b-414816943.ap-southeast-1.elb.amazonaws.com"

export const BASE_URL_USER_SERVICE = DOMAIN+"/user/api/v1/user"
export const BASE_URL_COURSE_SERVICE = DOMAIN+"/course/api/v1/course"
export const BASE_URL_TEACHER_MANAGEMENT_SERVICE =DOMAIN+"/teacher-management/api/v1/teacher"
export const BASE_URL_REVIEW_SERVICE = DOMAIN+"/review/api/v1/reviews"
export const BASE_URL_LECTURE_SERVICE = DOMAIN+"/lecture/api/v1/lectures"
export const BASE_URL_PAYMENT_SERVICE = DOMAIN+"/payment/api/v1/payment"
export const BASE_URL_STATISTICAL_SERVICE = DOMAIN+"/statistical/api/v1/statistical"
export const BASE_URL_AUTH_SERVICE = DOMAIN+"/auth/api/v1/auth"